# Generated by Django 2.2.14 on 2021-09-05 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190630_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('S', 'Fruits'), ('SW', 'Vegetables'), ('OW', 'Others')], max_length=2),
        ),
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('P', 'Winter'), ('S', 'Summer'), ('D', 'Other season')], max_length=1),
        ),
    ]
