# Generated by Django 2.2.14 on 2021-09-10 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210905_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('S', 'Food'), ('SW', 'House Materials'), ('OW', 'Others Materials')], max_length=2),
        ),
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('P', 'Organic'), ('S', 'Non Organic'), ('D', 'Other')], max_length=1),
        ),
    ]
