# Generated by Django 2.2.14 on 2021-09-24 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210912_0945'),
        ('core', '0006_auto_20210910_1153'),
    ]

    operations = [
    ]
